### PR TITLE
Screen

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@NGPixel

**Comment by Justman10000** [comment]
@NGPixel

**Comment by Justman10000** [comment]
@NGPixel

**Comment by NGPixel** [comment]
A screen is not the proper way to run a process meant to run indefinitely.
This will only cause confusion for most users.

**Comment by Justman10000** [comment]
> A screen is not the proper way to run a process meant to run indefinitely. This will only cause confusion for most users.

Then regulate the shit yourself! No more PRs or other support from me!

**Pull request closed without merging**
